### ISSUE TITLE
Can you explain how you got the logos to work?

### ISSUE THREAD

**Issue by androiski** [rishavnandi/wsl_dotfiles#15]
I really like your configs for zsh on WSL. I am trying to use the same ICONS and fonts you added in the starship.toml and the zshrc file. Can you explain how to install them?
I tried to install the TrueType font file to Windows 11, I did npm install on the font-logos folder within my WSL environment, nothing works.

**Comment by rishavnandi** [comment]
Hi!
For the icons beside the files when using ls commands
You just need to install [lsd](https://github.com/lsd-rs/lsd) on Ubuntu and any patched [nerd font](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3) on Windows and set the terminal to use that font.
Similarly when you have the nerd fonts installed you can copy anyone's starship config and any icons on the prompt and anywhere else should show up perfectly...I use the Fira Code nerd font

I linked a specific version of the nerd font as the newer ones have some bugs due to which the icons don't work properly.

**Comment by androiski** [comment]
Though I do notice one issue, I don't understand how it works, but I may need to look into this command on your zshrc
`_distro=$(awk '/^ID=/' /etc/*-release | awk -F'=' '{ print tolower($2) }')`

![image](https://github.com/rishavnandi/wsl_dotfiles/assets/29971637/f0a7f379-df55-4f2b-89d4-99ff31811b85)
Even though I am on Ubuntu, it says I am using Windows. I believe it catches the OS as Ubuntu on Windows statement.

Also a cool hack,
if youre using nitch or neofetch,
put `env SHELL=zsh neofetch` instead. WSL defaults to bash, so if you want to show the correct shell, you need to temp overwrite the shell variable
